const fs = require('fs');
const P = 'E:/WorkSpace/tower-odyssey/public/js/minigames/engine/mg-settings.js';
let s = fs.readFileSync(P, 'utf8');
function rep(a, b, msg) { if (s.indexOf(a) === -1) { console.error('MISS ' + msg); process.exit(1); } s = s.replace(a, b); }
rep("    assist: false,        // 辅助模式（B8）", "    assist: false,        // 辅助模式（B8）\n    perfGuard: false,     // 性能预算守卫（F3）", 'def');
rep("    setAssist(v) { this.assist = !!v; try { MG.assist && MG.assist.set(this.assist); } catch (e) {} this.save(); },", "    setAssist(v) { this.assist = !!v; try { MG.assist && MG.assist.set(this.assist); } catch (e) {} this.save(); },\n    setPerfGuard(v) { this.perfGuard = !!v; try { MG.perfGuard && MG.perfGuard.set(this.perfGuard); } catch (e) {} this.save(); },", 'set');
rep("                dynamicBg: this.dynamicBg, skin: this.skin, assist: this.assist,", "                dynamicBg: this.dynamicBg, skin: this.skin, assist: this.assist, perfGuard: this.perfGuard,", 'save');
rep("        html += '<label><input type=\"checkbox\" ' + (this.assist ? 'checked' : '') + '> 辅助模式</label>';", "        html += '<label><input type=\"checkbox\" ' + (this.assist ? 'checked' : '') + '> 辅助模式</label>';\n        html += '<label><input type=\"checkbox\" ' + (this.perfGuard ? 'checked' : '') + ' data-kind=\"perfGuard\"> 性能预算守卫</label>';", 'gear');
rep("        const chks = wrap.querySelectorAll('input[type=checkbox]');", "        const chks = wrap.querySelectorAll('input[type=checkbox]:not([data-kind])');", 'chks');
rep("        chks.forEach((c, i) => { c.onchange = () => { if (i === 0) this.setHaptics(c.checked); else if (i === 1) this.setAutoQuality(c.checked); else if (i === 2) this.setPixelated(c.checked); else if (i === 3) this.setDynamicBg(c.checked); else if (i === 4) this.setAssist(c.checked); else this.setA11y(map[i], c.checked); }; });", "        chks.forEach((c, i) => { c.onchange = () => { if (i === 0) this.setHaptics(c.checked); else if (i === 1) this.setAutoQuality(c.checked); else if (i === 2) this.setPixelated(c.checked); else if (i === 3) this.setDynamicBg(c.checked); else if (i === 4) this.setAssist(c.checked); else this.setA11y(map[i], c.checked); }; });\n        const _pg = wrap.querySelector('input[type=checkbox][data-kind=\"perfGuard\"]'); if (_pg) _pg.onchange = () => this.setPerfGuard(_pg.checked);", 'pg');
fs.writeFileSync(P, s); console.log('mg-settings(F3) patched OK');
